TK1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TK1_home.urls')),
    path('faq/', include('TK1_faq.urls')),
    path('ktp/', include('TK1_ktp.urls')),
    path('sim/', include('TK1_sim.urls')),
    path('pajak/', include('TK1_pajak.urls')),
]

TK1_faq/urls.py
from django.contrib import admin
from django.urls import *
from . import views

app_name='TK1_faq'
urlpatterns = [
    path('', views.index, name='faq-index'),
]

TK1_home/urls.py
from django.contrib import admin
from django.urls import *
from .views import *

app_name='TK1_home'
urlpatterns = [
    path('', index, name='index'),
]

TK1_ktp/urls.py
from django.contrib import admin
from django.urls import *
from .views import index,hasil

app_name='TK1_ktp'
urlpatterns = [
    path('ktp/', index, name='ktp'),
    path('hasil/',hasil, name='hasil'),

]

TK1_home/models.py
from django.db import models

# Create your models here.

TK1_home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from datetime import datetime, date
# from .forms import *
# from .models import *
from django.urls import reverse

# Create your views here.
def index(request):
	response = {}
	return render(request, 'index.html', response)

TK1_home/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>SIPEMERINTAH.com</title>

	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}" />

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>

<body>
	<style>

		.carousel-item{
    	height: 500px;
    }

		.carousel-item img{
    	height: 600px;
    }

    .footer{
      background-color: #72E4E4;
      height: 150px;
    }

    .middle{
      background-color: #1167B1;
      height: 300px;
    }

    .paragraph_index{
      margin: 0px 150px;
      padding: 100px 0px;
      text-align: justify;
      text-indent: 35px;
      color:white;
    }

    .images{
      padding: 20px;
    }

    .social_media{
      padding-top:60px;
    }

	</style>

  <div>
      <nav class="navbar fixed-top navbar-expand-md navbar-dark">
          <a class="navbar-brand" href="{% url 'TK1_home:index' %}">
              <img style="height: 50px;" src="{% static 'images/sipemerintah.png' %}">
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent" style="padding-right:50px;">
              <ul class="navbar-nav ml-auto">
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'TK1_home:index' %}#">HOME</a>
                  </li>

                  <li class="nav-item dropdown">
          			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Pelayanan</a>
          			<div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'TK1_ktp:ktp' %}">Pembuatan KTP</a>
                    <a class="dropdown-item" href="{% url 'add_sim' %}">Pembuatan SIM</a>
                    <a class="dropdown-item" href="{% url 'add_pajak' %}">Pajak Kendaraan</a>
            				<a class="dropdown-item" href="#">Something else here</a>
          			</div>
        			</li>

                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'TK1_faq:faq-index' %}#">FAQ</a>
                  </li>

              </ul>
          </div>
      </nav>
  </div>


  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="{% static 'images/first-image.jpeg' %}" alt="First slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{% static 'images/second-image.jpeg' %}" alt="Second slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{% static 'images/third-image.jpeg' %}" alt="Third slide">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>


  <div class="container-fluid middle">
    <p class="paragraph_index">
        Sipemerintah adalah website yang memiliki tujuan untuk memudahkan masyarakat dalam melakukan kegiatan administrasi dan pembayaran pajak. Sipemerintah membantu masyarakat dengan cara memberikan layanan untuk melakukan kegiatan tersebut secara online. Layanan tersebut berisi tentang otomasi tahapan yang dapat dilakukan di mana saja asalkan terhubung dengan internet. Otomasi ini yaitu pengumpulan berkas yang dilakukan secara online sehingga mengurangi waktu yang dibutuhkan masyarakat dalam melakukan proses administrasi dan memudahkan masyarakat dalam mengumpulkan dokumen yang terkait untuk proses administrasi yang diinginkan. Website ini memiliki beberapa fitur antara lain pendaftaran penduduk, pembuatan dan perpanjangan SIM, pembayaran pajak kendaraan, serta FAQ.
    </p>

  </div>


  <div class="container-fluid footer">
    <div class="row social_media">
      <div class="col-md-12 text-center">
        <a class="images" href="{% url 'TK1_home:index' %}">
          <img style="height: 35px;" src="{% static 'images/facebook.png' %}">
        </a>

        <a class="images" href="{% url 'TK1_home:index' %}">
          <img style="height: 35px;" src="{% static 'images/instagram.png' %}">
        </a>

        <a class="images" href="{% url 'TK1_home:index' %}">
          <img style="height: 35px;" src="{% static 'images/whatsapp.png' %}">
        </a>

        <a class="images" href="{% url 'TK1_home:index' %}">
          <img style="height: 35px;" src="{% static 'images/gmail.png' %}">
        </a>
      </div>

    </div>

    <div class="footer-copyright text-center py-3">© 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/"> SIPEMERINTAH.com</a>
    </div>

  </div>



</body>
</html>